# Generated by Django 2.2 on 2020-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20201028_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('RD', 'готов к выдаче'), ('CNC', 'отменен')], default='FM', max_length=3, verbose_name='Статус'),
        ),
    ]
